[project]
name = "mpda-architecture"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "crawl4ai>=0.8.6",
    "ddgs>=9.14.4",
    "fastapi[standard]>=0.136.1",
    "fastmcp>=3.3.1",
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "tavily>=1.1.0",
]

[dependency-groups]
dev = [
    "ipython>=9.13.0",
]
